name: Build check

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-prod-containers:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build containers
      run: |
        export TAG=$(git rev-parse --short "$GITHUB_SHA")
        docker compose -f compose.prod.yaml build
        export TAG=latest
        docker compose -f compose.prod.yaml build

    - name: Push to hub
      run: |
        export TAG=$(git rev-parse --short "$GITHUB_SHA")
        docker compose -f compose.prod.yaml push
        export TAG=latest
        docker compose -f compose.prod.yaml push

  build-dev-containers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build containers
        run: docker compose build

      - name: Push to hub
        run: docker compose push
